name: Publish
on:
  push:
    branches:
      - '**'
      - '!main' 

jobs:
  Publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install toml-cli
      - uses: actions-rs/cargo@v1
        with:
          command: cargo install toml-cli
          
      - name: Check version
        run: test "v$(toml get -r Cargo.toml package.version)"= "${{ github.ref_name }}"
     
      - name: Publish dry run
        run: cargo publish --dry-run
